---
- name: include vars
  include_vars:
    file: "{{ app_env }}.yml"
  tags:
    - always # this is a special tag to always run this task

- name: get helm binary
  unarchive:
    src: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: install helm
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/bin/helm
    mode: 0755
    remote_src: yes

- name: install unzip
  package:
    name: unzip
    state: present

- name: download and unarchive Packer
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
    dest: /tmp
    remote_src: true

- name: install packer
  copy:
    src: /tmp/packer
    dest: /usr/bin/packer
    mode: 0755
    remote_src: yes

- name: install epel
  package:
    name: epel-release

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - jq
    - hub

- include_tasks: development.yml
  when: app_env == 'development'

- include_tasks: gce.yml
  when: app_env != 'development'
