---
- name: get redis exporter binary
  unarchive:
    src: https://github.com/oliver006/redis_exporter/releases/download/v1.9.0/redis_exporter-v1.9.0.linux-amd64.tar.gz
    remote_src: yes
    dest: /tmp
  tags:
    - exporter

- name: install exporter binary
  copy:
    src: /tmp/redis_exporter-v1.9.0.linux-amd64/redis_exporter
    dest: /usr/bin/
    remote_src: yes
    mode: 0755
  tags:
    - exporter

- name: upload systemd config for redis exporter
  copy:
    src: redis-exporter.service
    dest: /etc/systemd/system/redis-exporter.service
  tags:
    - exporter

- name: Enable and start exporter
  systemd:
    name: redis-exporter
    state: started
    enabled: yes
    daemon-reload: yes
  tags:
    - exporter
