FROM nginx:1.11

LABEL description="Front End UI Container."

RUN apt-get update -qq \
    && apt-get upgrade -y -qq \
    && apt-get -y -qq install curl git bzip2 python libfontconfig1-dev xz-utils build-essential \
    && apt-get clean -qq

RUN groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

# gpg keys listed at https://github.com/nodejs/node#release-team
RUN set -ex \
  && for key in \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    56730D5401028683275BD23C23EFEFE93C4CFFFE \
  ; do \
    gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
    gpg --keyserver keyserver.pgp.com --recv-keys "$key" || \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ; \
  done

# Install Node
ENV NPM_CONFIG_LOGLEVEL warn
ENV NODE_VERSION 6.9.1

RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-x64.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs

ARG VIRTUAL_HOST
ARG NODE_ENV
ARG OAUTH_TOKEN
ARG ENV_BRANCH
ENV NODE_ENV ${NODE_ENV:-development}
ENV VIRTUAL_HOST ${VIRTUAL_HOST:-ui.local.linkpool.org}

# Configure nginx
COPY configs/linkpool.conf /tmp/linkpool.nginx
RUN envsubst '$VIRTUAL_HOST' < /tmp/linkpool.nginx > /etc/nginx/conf.d/default.conf
# Install gulp/bower globally
RUN npm install -g gulp bower

RUN mkdir -p /app/ && chown node.node -R /app
USER node
WORKDIR /app
ARG TIMESTAMP
RUN TIMESTAMP=$TIMESTAMP git clone https://$OAUTH_TOKEN:x-oauth-basic@github.com/Testtask/linkpool.git src && cd src && git checkout -f $ENV_BRANCH
WORKDIR /app/src
RUN NODE_ENV=$NODE_ENV npm install
RUN ln -sf /app/src/dist /app/current

USER root
