---
galaxy_info:
  role_name: jenkins-git
  author: linkpool
  description: jenkins-git meta
  company: linkpool
  license: linkpool private property
  min_ansible_version: 2.9
  platforms:
    - name: EL
      version:
        - 7
        - 8

dependencies:
  - role: jenkins-plugins
